# This file was generated by GoReleaser. DO NOT EDIT.
cask "gentle-qe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0193961a093316deddd55067b882556e66e5c2ec765c4ee9e60e6253103cf9a7"
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v#{version}/gentle-qe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4e0951a822d462d09a8c419eacf78644fa0ba418ff2ed70752360e3d3918eaa"
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v#{version}/gentle-qe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f05903e839281a20d841364d81407938590904e8c210b7bc8d628bef837e54b"
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v#{version}/gentle-qe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ef1654b7553a206713a9e1d513bfe3ddbc6a3c89fe3997c0b78668e1c245854"
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v#{version}/gentle-qe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gentle-qe"
  desc "Gentle-QE — Unified AI Ecosystem for Testing and Reliability."
  homepage "https://github.com/EduardoVeraE/gentle-qe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gentle-qe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gentle-qe"]
    end
  end

  # No zap stanza required

end
