# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleQe < Formula
  desc "Gentle-QE — Unified AI Ecosystem for Testing and Reliability."
  homepage "https://github.com/EduardoVeraE/gentle-qe"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.2/gentle-qe_0.1.2_darwin_amd64.tar.gz"
      sha256 "476b379fb630761777a4dc0553e309f4414ba46a83634ae63cab9fbeb8707051"

      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.2/gentle-qe_0.1.2_darwin_arm64.tar.gz"
      sha256 "253a7d9d678447ebdd03859a15bf9398edc40f8fddbc36d040abcbc661282b56"

      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.2/gentle-qe_0.1.2_linux_amd64.tar.gz"
      sha256 "fce606b94018ffd47c6fb8b65c938ae276ff3c8b6adc67e419289f66d890e9aa"
      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.2/gentle-qe_0.1.2_linux_arm64.tar.gz"
      sha256 "673b11ae73c7388d27af694d941ddb7e68505243bd56a44153a45044507a3245"
      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
  end
end
