# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleQe < Formula
  desc "Gentle-QE — Unified AI Ecosystem for Testing and Reliability."
  homepage "https://github.com/EduardoVeraE/gentle-qe"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.3/gentle-qe_0.1.3_darwin_amd64.tar.gz"
      sha256 "1978a4575e17655ac56f13f18e94be8342d39d2a145419a47aceeb2331f631fc"

      define_method(:install) do
        bin.install "gentle-qe"
        bin.install_symlink "gentle-qe" => "evqe"
        bin.install_symlink "gentle-qe" => "qe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.3/gentle-qe_0.1.3_darwin_arm64.tar.gz"
      sha256 "b7b4eb06607e4b7c80325fc0e3e7bde56c41357829105ee33457ceba1795f1f5"

      define_method(:install) do
        bin.install "gentle-qe"
        bin.install_symlink "gentle-qe" => "evqe"
        bin.install_symlink "gentle-qe" => "qe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.3/gentle-qe_0.1.3_linux_amd64.tar.gz"
      sha256 "aa06cccff8286ac5fc73f83e03dae6725b3456f859fc766ed99bf68f8788b769"
      define_method(:install) do
        bin.install "gentle-qe"
        bin.install_symlink "gentle-qe" => "evqe"
        bin.install_symlink "gentle-qe" => "qe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v0.1.3/gentle-qe_0.1.3_linux_arm64.tar.gz"
      sha256 "e9869109ff78d2108a10f0f27f6dd14784c0f43fd9f2b385dc4dad0f390b13f9"
      define_method(:install) do
        bin.install "gentle-qe"
        bin.install_symlink "gentle-qe" => "evqe"
        bin.install_symlink "gentle-qe" => "qe"
      end
    end
  end
end
