# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleQa < Formula
  desc "Gentle-QA — One command. Any test. Any framework."
  homepage "https://github.com/EduardoVeraE/Gentle-QA"
  version "1.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.22.0/gentle-qa_1.22.0_darwin_amd64.tar.gz"
      sha256 "b2edf0963c9c7a22672aa1cfd1784830774beddbe8457c137a7fca5676c1d7af"

      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.22.0/gentle-qa_1.22.0_darwin_arm64.tar.gz"
      sha256 "d83d25d51bb9997f5fc5382c3e5a29b4a56060b65582409e1665dbd164485a05"

      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.22.0/gentle-qa_1.22.0_linux_amd64.tar.gz"
      sha256 "dbd20f648f60699b8e867ca55d772733c8adaa99fbde6699152c941b8891af0d"
      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.22.0/gentle-qa_1.22.0_linux_arm64.tar.gz"
      sha256 "1934e2b506a7811d98ee399d6576e183ef50938c5614b4b34ef6d4ac2a134215"
      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
  end
end
