# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleQa < Formula
  desc "Gentle-QA — One command. Any test. Any framework."
  homepage "https://github.com/EduardoVeraE/Gentle-QA"
  version "1.25.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.25.0/gentle-qa_1.25.0_darwin_amd64.tar.gz"
      sha256 "880ce7effc9dc8b17d633531cb48458feb0c4ef9b61bc25e3cbb5f7ac00a4ad7"

      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.25.0/gentle-qa_1.25.0_darwin_arm64.tar.gz"
      sha256 "bbe8ac79f8d3bc9b0ae3d0e9c3e8981d789189693f8b71433003b57131f46061"

      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.25.0/gentle-qa_1.25.0_linux_amd64.tar.gz"
      sha256 "fcf939656cb484385b19c6f304223d7225d5f2e30c5639c5e459a7dde80654a7"
      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qa/releases/download/v1.25.0/gentle-qa_1.25.0_linux_arm64.tar.gz"
      sha256 "ef27639a1912c04aa1a73b1599d288ece67ad9253bce9a1a96e5895781247286"
      define_method(:install) do
        bin.install "gentle-qa"
      end
    end
  end
end
