# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleQe < Formula
  desc "Gentle-AI — Ecosystem, Frameworks, Workflows for AI coding agents."
  homepage "https://github.com/EduardoVeraE/gentle-qe"
  version "1.30.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v1.30.1/gentle-qe_1.30.1_darwin_amd64.tar.gz"
      sha256 "3f490bd2df371ae1dfc93e320ceb1e80a424f28e6e802fdd0f02ded762b24c33"

      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v1.30.1/gentle-qe_1.30.1_darwin_arm64.tar.gz"
      sha256 "fb36076127efe69f7ff4920fb3748bc141efc0298661a11b0a4564c6dd317fc7"

      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v1.30.1/gentle-qe_1.30.1_linux_amd64.tar.gz"
      sha256 "8d45df6067787fcc73665bd2467135450384504e52fca20a89ed59fd86e8bfce"
      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardoVeraE/gentle-qe/releases/download/v1.30.1/gentle-qe_1.30.1_linux_arm64.tar.gz"
      sha256 "0dde6a842d9377dbe66ccb65e4a3e64eb6f84861b431727718145d1cd3e3aae3"
      define_method(:install) do
        bin.install "gentle-qe"
      end
    end
  end
end
